/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BitMap newFile= new BitMap(args[0],args[1],args[2]);

        newFile.printInfo();
        newFile.testFile();
    }
}
